const data = {
  turmas: [
    {
      curso: "Mecânica Geral",
      local: "IF1",
      periodo: "Manhã",
      sala: 2,
      aulas: {
        r1: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r2: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r3: ["UTAV", "DCFGFP", "AMDMM", "AMDMM", "UMP"],
        r4: ["UTAV", "DCFGFP", "AMDMM", "RPCE", "UMP"],
        r5: ["IPEODAC", "AMDMM", "ULISSPP", "RPCE", "UMP"],
        r6: ["IPEODAC", "AMDMM", "ULISSPP", "", ""],
      },
    },
    {
      curso: "Gestão de recursos humanos",
      local: "IF1",
      periodo: "Tarde",
      sala: 3,
      aulas: {
        r1: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r2: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r3: ["UTAV", "DCFGFP", "AMDMM", "AMDMM", "UMP"],
        r4: ["UTAV", "DCFGFP", "AMDMM", "RPCE", "UMP"],
        r5: ["IPEODAC", "AMDMM", "ULISSPP", "RPCE", "UMP"],
        r6: ["IPEODAC", "AMDMM", "ULISSPP", "", ""],
      },
    },
    {
      curso: "Gestão geral",
      local: "IF2",
      periodo: "Noite",
      sala: 2,
      aulas: {
        r1: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r2: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r3: ["UTAV", "DCFGFP", "AMDMM", "AMDMM", "UMP"],
        r4: ["UTAV", "DCFGFP", "AMDMM", "RPCE", "UMP"],
        r5: ["IPEODAC", "AMDMM", "ULISSPP", "RPCE", "UMP"],
        r6: ["IPEODAC", "AMDMM", "ULISSPP", "", ""],
      },
    },
    {
      curso: "Contabilidade e Auditoria",
      local: "LORE",
      periodo: "Manhã",
      sala: 1,
      aulas: {
        r1: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r2: ["PPMT", "UTAV", "UMP", "AMDMM", "UTAV"],
        r3: ["UTAV", "DCFGFP", "AMDMM", "AMDMM", "UMP"],
        r4: ["UTAV", "DCFGFP", "AMDMM", "RPCE", "UMP"],
        r5: ["IPEODAC", "AMDMM", "ULISSPP", "RPCE", "UMP"],
        r6: ["IPEODAC", "AMDMM", "ULISSPP", "", ""],
      },
    },
  ],
};
